/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.minister;

import DAO.AccountDAO;
import POJO.Account;
import UI.MainFrame;
import com.mysql.cj.jdbc.SuspendableXAConnection;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author Windows 10
 */
public class AdminManagementPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    /**
     * Creates new form AdminManagementPanel
     */
    public AdminManagementPanel(MainFrame mainFrame) {
        this.mainFrame=mainFrame;
        initComponents();
        setUpAction();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        centerPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        resetPassBtn = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        centerPanel.setMaximumSize(new java.awt.Dimension(2147483647, 400));
        centerPanel.setPreferredSize(new java.awt.Dimension(577, 300));
        centerPanel.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        DefaultTableModel adminTM=new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        );
        jTable1.setModel(adminTM);
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        centerPanel.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setMaximumSize(new java.awt.Dimension(150, 32767));
        jPanel6.setMinimumSize(new java.awt.Dimension(125, 100));
        jPanel6.setPreferredSize(new java.awt.Dimension(150, 300));
        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        addBtn.setText("Add");
        addBtn.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel6.add(addBtn);

        resetPassBtn.setText("Reset Password");
        resetPassBtn.setPreferredSize(new java.awt.Dimension(120, 30));
        jPanel6.add(resetPassBtn);

        centerPanel.add(jPanel6, java.awt.BorderLayout.WEST);

        jPanel1.add(centerPanel, java.awt.BorderLayout.CENTER);

        topPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        topPanel.setPreferredSize(new java.awt.Dimension(684, 100));
        topPanel.setLayout(new java.awt.BorderLayout());

        jPanel7.setPreferredSize(new java.awt.Dimension(787, 35));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/resources/previous.png"))); // NOI18N
        backBtn.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel7.add(backBtn);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("ADMIN MANAGEMENT");
        jLabel1.setMinimumSize(new java.awt.Dimension(252, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel7.add(jLabel1);

        topPanel.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(topPanel, java.awt.BorderLayout.PAGE_START);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void setUpAction()
    {
        backBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainFrame.changePanel(new MinisterMenuPanel(mainFrame));
            }
        });

        accountTM=new DefaultTableModel(
                new Object[][]{},
                new Object[]{"Username","Is Admin","Is Active"}
        );
        jTable1.setModel(accountTM);
        //load data to table
        List<Account> adminList= AccountDAO.getAllAdminAccounts();
        for(int i=0;i<adminList.size();i++)
        {
            accountTM.addRow(AccountDAO.convertAccountToRowData(adminList.get(i)));
        }

        resetPassBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int selected=jTable1.getSelectedRow();
                if(selected>=0) {
                    String usernameReset = String.valueOf(accountTM.getValueAt(selected, 0));
                    AccountDAO.resetPassword(usernameReset);
                    if(usernameReset.equals(mainFrame.getAccount().getUsername()))
                    {
                        Account account=mainFrame.getAccount();
                        account.setPassword(AccountDAO.hashPassword(account.getUsername()));
                        mainFrame.setAccount(account);
                    }
                    System.out.println("Password update!");
                }
            }
        });

        addBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JTextField username = new JTextField();
                JTextField password = new JPasswordField();
                Object[] message = {
                        "Username:", username,
                        "Password:", password
                };

                int option=JOptionPane.showOptionDialog(null,message,"Add new admin",JOptionPane.OK_OPTION,JOptionPane.QUESTION_MESSAGE,null,
                        new Object[]{"Confirm","Cancel"},1);

                if(option==0)
                {
                    String userName=username.getText();
                    String pass=password.getText();
                    //add to database
                    boolean res=AccountDAO.createAdminAccount(userName,pass);
                    //add to row
                    if(res)
                        accountTM.addRow(new Object[]{userName,true,true});
                }

                System.out.println(option);
            }
        });

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton resetPassBtn;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

    private DefaultTableModel accountTM;
}
