/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.minister;

import UI.ChangePassPanel;
import UI.MainFrame;
import UI.MainPanel;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Windows 10
 */
public class MinisterMenuPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    /**
     * Creates new form MinistryPanel
     */
    public MinisterMenuPanel(MainFrame mainFrame) {
        this.mainFrame=mainFrame;
        initComponents();
        setUpAction();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        subjectManageBtn = new javax.swing.JButton();
        classManageBtn = new javax.swing.JButton();
        studentAttendBtn = new javax.swing.JButton();
        changePassBtn = new javax.swing.JButton();
        signOutBtn = new javax.swing.JButton();
        adminManageBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("ADMIN MENU");
        jPanel2.add(jLabel1);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        subjectManageBtn.setText("Subject Mangement");
        subjectManageBtn.setMaximumSize(new java.awt.Dimension(300, 50));
        subjectManageBtn.setMinimumSize(new java.awt.Dimension(200, 40));
        subjectManageBtn.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(subjectManageBtn, gridBagConstraints);

        classManageBtn.setText("Class Management");
        classManageBtn.setMaximumSize(new java.awt.Dimension(300, 50));
        classManageBtn.setMinimumSize(new java.awt.Dimension(200, 40));
        classManageBtn.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(classManageBtn, gridBagConstraints);

        studentAttendBtn.setText("Student Attendance");
        studentAttendBtn.setMaximumSize(new java.awt.Dimension(300, 50));
        studentAttendBtn.setMinimumSize(new java.awt.Dimension(200, 40));
        studentAttendBtn.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(studentAttendBtn, gridBagConstraints);

        changePassBtn.setText("Change Password");
        changePassBtn.setMaximumSize(new java.awt.Dimension(300, 50));
        changePassBtn.setMinimumSize(new java.awt.Dimension(200, 40));
        changePassBtn.setPreferredSize(new java.awt.Dimension(150, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(changePassBtn, gridBagConstraints);

        signOutBtn.setText("Sign out");
        signOutBtn.setMaximumSize(new java.awt.Dimension(300, 50));
        signOutBtn.setMinimumSize(new java.awt.Dimension(200, 40));
        signOutBtn.setPreferredSize(new java.awt.Dimension(150, 40));
        signOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(signOutBtn, gridBagConstraints);

        adminManageBtn.setText("Admin Management");
        adminManageBtn.setMaximumSize(new java.awt.Dimension(300, 50));
        adminManageBtn.setMinimumSize(new java.awt.Dimension(200, 40));
        adminManageBtn.setPreferredSize(new java.awt.Dimension(150, 40));
        adminManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminManageBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(adminManageBtn, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void setUpAction()
    {
        adminManageBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainFrame.changePanel(new AdminManagementPanel(mainFrame));
            }
        });
        subjectManageBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainFrame.changePanel(new SubjectManagementPanel(mainFrame));
            }
        });
        classManageBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainFrame.changePanel(new ClassManagementPanel(mainFrame));
            }
        });
        studentAttendBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainFrame.changePanel(new StudentAttendancePanel(mainFrame));
            }
        });
        signOutBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainFrame.changePanel(new MainPanel(mainFrame));
            }
        });
        changePassBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainFrame.changePanel(new ChangePassPanel(mainFrame));
            }
        });

    }

    private void signOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signOutBtnActionPerformed

    private void adminManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminManageBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminManageBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminManageBtn;
    private javax.swing.JButton changePassBtn;
    private javax.swing.JButton classManageBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton signOutBtn;
    private javax.swing.JButton studentAttendBtn;
    private javax.swing.JButton subjectManageBtn;
    // End of variables declaration//GEN-END:variables
}
