/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.minister;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
/**
 *
 * @author Windows 10
 */
public class ModifyClassPanel extends JPanel {

    /**
     * Creates new form ModifyClassPanel
     */
    public ModifyClassPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new JPanel();
        jPanel5 = new JPanel();
        jScrollPane1 = new JScrollPane();
        jTable1 = new JTable();
        jPanel6 = new JPanel();
        editBtn = new JButton();
        removeBtn = new JButton();
        applyBtn = new JButton();
        addBtn = new JButton();
        importBtn = new JButton();
        topPanel = new JPanel();
        jLabel1 = new JLabel();
        jPanel1 = new JPanel();
        jPanel4 = new JPanel();
        jLabel2 = new JLabel();
        jComboBox1 = new JComboBox<>();
        jLabel3 = new JLabel();
        jComboBox2 = new JComboBox<>();
        jPanel2 = new JPanel();
        showClassBtn = new JButton();
        addClassBtn = new JButton();

        setLayout(new java.awt.BorderLayout());

        centerPanel.setMaximumSize(new java.awt.Dimension(2147483647, 400));
        centerPanel.setPreferredSize(new java.awt.Dimension(577, 300));
        centerPanel.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        centerPanel.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setMaximumSize(new java.awt.Dimension(150, 32767));
        jPanel6.setMinimumSize(new java.awt.Dimension(125, 100));
        jPanel6.setPreferredSize(new java.awt.Dimension(125, 300));

        editBtn.setText("Edit");

        removeBtn.setText("Remove");

        applyBtn.setText("Apply");

        addBtn.setText("Add");

        importBtn.setText("Import...");

        GroupLayout jPanel6Layout = new GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(applyBtn)
                        .addComponent(removeBtn)
                        .addComponent(editBtn))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addGap(1, 1, 1))
                    .addComponent(importBtn))
                .addGap(23, 23, 23))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(addBtn)
                .addGap(18, 18, 18)
                .addComponent(editBtn)
                .addGap(18, 18, 18)
                .addComponent(removeBtn)
                .addGap(18, 18, 18)
                .addComponent(importBtn)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(applyBtn)
                .addGap(16, 16, 16))
        );

        centerPanel.add(jPanel6, java.awt.BorderLayout.EAST);

        add(centerPanel, java.awt.BorderLayout.CENTER);

        topPanel.setPreferredSize(new java.awt.Dimension(684, 100));
        topPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("CLASS MANAGEMENT");
        topPanel.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(580, 200));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));
        jPanel4.setPreferredSize(new java.awt.Dimension(460, 100));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Subject:");
        jPanel4.add(jLabel2);

        jComboBox1.setModel(new DefaultComboBoxModel<>(new String[] { "Subject 1" }));
        jPanel4.add(jComboBox1);

        jLabel3.setText("jLabel3");
        jPanel4.add(jLabel3);

        jComboBox2.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox2);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        topPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(BorderFactory.createEmptyBorder(5, 10, 5, 10));
        jPanel2.setMaximumSize(new java.awt.Dimension(100, 32767));
        jPanel2.setPreferredSize(new java.awt.Dimension(125, 93));
        jPanel2.setLayout(new java.awt.GridLayout(2, 1, 10, 10));

        showClassBtn.setText("Show");
        showClassBtn.setAlignmentX(0.5F);
        showClassBtn.setPreferredSize(new java.awt.Dimension(72, 25));
        jPanel2.add(showClassBtn);

        addClassBtn.setText("Add Class....");
        jPanel2.add(addClassBtn);

        topPanel.add(jPanel2, java.awt.BorderLayout.EAST);

        add(topPanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton addBtn;
    private JButton addClassBtn;
    private JButton applyBtn;
    private JPanel centerPanel;
    private JButton editBtn;
    private JButton importBtn;
    private JComboBox<String> jComboBox1;
    private JComboBox<String> jComboBox2;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JPanel jPanel6;
    private JScrollPane jScrollPane1;
    private JTable jTable1;
    private JButton removeBtn;
    private JButton showClassBtn;
    private JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
