/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.minister;
import javax.swing.*;
import javax.swing.table.*;


/**
 *
 * @author Windows 10
 */
public class StudentAttendancePanel extends JPanel {

    /**
     * Creates new form AttendanceResultPanel
     */
    public StudentAttendancePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jPanel3 = new JPanel();
        Semester = new JLabel();
        semesterCB = new JComboBox<>();
        jLabel2 = new JLabel();
        subjectCB = new JComboBox<>();
        jLabel3 = new JLabel();
        classCB = new JComboBox<>();
        jPanel2 = new JPanel();
        jPanel4 = new JPanel();
        jScrollPane1 = new JScrollPane();
        jTable2 = new JTable();
        annotatePanel = new JPanel();
        jButton1 = new JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(37, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(746, 70));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ATTENDANCE RESULT");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(746, 40));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        Semester.setText("Semester:");
        jPanel3.add(Semester);

        semesterCB.setModel(new DefaultComboBoxModel<>(new String[] { "Semester 1" }));
        semesterCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semesterCBActionPerformed(evt);
            }
        });
        jPanel3.add(semesterCB);

        jLabel2.setText("Subject:");
        jPanel3.add(jLabel2);

        subjectCB.setModel(new DefaultComboBoxModel<>(new String[] { "Subject1" }));
        subjectCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectCBActionPerformed(evt);
            }
        });
        jPanel3.add(subjectCB);

        jLabel3.setText("Class:");
        jPanel3.add(jLabel3);

        classCB.setModel(new DefaultComboBoxModel<>(new String[] { "Class1" }));
        jPanel3.add(classCB);

        jPanel1.add(jPanel3, java.awt.BorderLayout.SOUTH);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setMinimumSize(new java.awt.Dimension(0, 400));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setMaximumSize(new java.awt.Dimension(300, 32767));

        jTable2.setModel(new DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jPanel4.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        annotatePanel.setMaximumSize(new java.awt.Dimension(100, 32767));
        annotatePanel.setMinimumSize(new java.awt.Dimension(100, 10));
        annotatePanel.setPreferredSize(new java.awt.Dimension(120, 600));

        jButton1.setIcon(new ImageIcon(getClass().getResource("/com/mycompany/swingutilproject/resource/check-mark.png"))); // NOI18N
        jButton1.setText("Apply");
        jButton1.setPreferredSize(new java.awt.Dimension(105, 35));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        annotatePanel.add(jButton1);

        jPanel2.add(annotatePanel, java.awt.BorderLayout.EAST);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void semesterCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semesterCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semesterCBActionPerformed

    private void subjectCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectCBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel Semester;
    private JPanel annotatePanel;
    private JComboBox<String> classCB;
    private JButton jButton1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JScrollPane jScrollPane1;
    private JTable jTable2;
    private JComboBox<String> semesterCB;
    private JComboBox<String> subjectCB;
    // End of variables declaration//GEN-END:variables
}
