/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.minister;

import UI.MainFrame;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Windows 10
 */
public class SubjectManagementPanel extends javax.swing.JPanel {

    private MainFrame mainFrame;
    /**
     * Creates new form ModifySubjectPanel
     */
    public SubjectManagementPanel(MainFrame mainFrame) {
        this.mainFrame=mainFrame;
        initComponents();
        setUpAction();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        subjectIDTF = new javax.swing.JTextField();
        startDayTF = new javax.swing.JTextField();
        endDayTF = new javax.swing.JTextField();
        subjectNameTF = new javax.swing.JTextField();
        numberWeekCB = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        startSessionCB = new javax.swing.JComboBox<>();
        endSessionCB = new javax.swing.JComboBox<>();
        roomNameTF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        addSubjectBtn = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        editBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        applyBtn = new javax.swing.JButton();

        jLabel11.setText("jLabel11");

        setLayout(new java.awt.BorderLayout());

        topPanel.setPreferredSize(new java.awt.Dimension(684, 160));
        topPanel.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(580, 200));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        jPanel3.setLayout(new java.awt.GridLayout(2, 5, 20, 0));

        jLabel2.setText("Subject ID:");
        jPanel3.add(jLabel2);

        jLabel4.setText("Start Day:");
        jPanel3.add(jLabel4);

        jLabel5.setText("End day:");
        jPanel3.add(jLabel5);

        jLabel3.setText("Subject Name:");
        jPanel3.add(jLabel3);

        jLabel7.setText("Number of weeks:");
        jPanel3.add(jLabel7);

        subjectIDTF.setMinimumSize(new java.awt.Dimension(80, 24));
        subjectIDTF.setPreferredSize(new java.awt.Dimension(81, 24));
        jPanel3.add(subjectIDTF);

        startDayTF.setToolTipText("The beginning of subject");
        startDayTF.setMinimumSize(new java.awt.Dimension(80, 24));
        startDayTF.setPreferredSize(new java.awt.Dimension(81, 24));
        startDayTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDayTFActionPerformed(evt);
            }
        });
        jPanel3.add(startDayTF);

        endDayTF.setMinimumSize(new java.awt.Dimension(80, 24));
        endDayTF.setPreferredSize(new java.awt.Dimension(81, 24));
        jPanel3.add(endDayTF);

        subjectNameTF.setMinimumSize(new java.awt.Dimension(80, 24));
        subjectNameTF.setPreferredSize(new java.awt.Dimension(81, 24));
        subjectNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectNameTFActionPerformed(evt);
            }
        });
        jPanel3.add(subjectNameTF);

        numberWeekCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        jPanel3.add(numberWeekCB);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        jPanel4.setPreferredSize(new java.awt.Dimension(460, 100));
        jPanel4.setLayout(new java.awt.GridLayout(2, 5, 10, 5));

        jLabel6.setText("Day in Week:");
        jPanel4.add(jLabel6);

        jLabel8.setText("Start Session:");
        jPanel4.add(jLabel8);

        jLabel9.setText("End Session:");
        jPanel4.add(jLabel9);

        jLabel10.setText("Room Name:");
        jPanel4.add(jLabel10);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        jPanel4.add(jComboBox2);

        startSessionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel4.add(startSessionCB);

        endSessionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel4.add(endSessionCB);

        roomNameTF.setMinimumSize(new java.awt.Dimension(80, 24));
        roomNameTF.setPreferredSize(new java.awt.Dimension(81, 24));
        jPanel4.add(roomNameTF);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        topPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setMaximumSize(new java.awt.Dimension(100, 32767));
        jPanel2.setPreferredSize(new java.awt.Dimension(125, 93));

        addSubjectBtn.setText("Add");
        addSubjectBtn.setToolTipText("Add new subject with data from left side");
        addSubjectBtn.setPreferredSize(new java.awt.Dimension(72, 25));
        jPanel2.add(addSubjectBtn);

        topPanel.add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel7.setPreferredSize(new java.awt.Dimension(787, 32));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/resources/previous.png"))); // NOI18N
        backBtn.setPreferredSize(new java.awt.Dimension(25, 25));
        jPanel7.add(backBtn);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SUBJECT MANAGEMENT");
        jLabel1.setMinimumSize(new java.awt.Dimension(252, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 30));
        jPanel7.add(jLabel1);

        topPanel.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        add(topPanel, java.awt.BorderLayout.PAGE_START);

        centerPanel.setMaximumSize(new java.awt.Dimension(2147483647, 400));
        centerPanel.setPreferredSize(new java.awt.Dimension(577, 300));
        centerPanel.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        centerPanel.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setMaximumSize(new java.awt.Dimension(150, 32767));
        jPanel6.setMinimumSize(new java.awt.Dimension(125, 100));
        jPanel6.setPreferredSize(new java.awt.Dimension(125, 300));

        editBtn.setText("Edit");

        removeBtn.setText("Remove");

        applyBtn.setText("Apply");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(applyBtn)
                    .addComponent(removeBtn)
                    .addComponent(editBtn))
                .addGap(23, 23, 23))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(editBtn)
                .addGap(18, 18, 18)
                .addComponent(removeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 271, Short.MAX_VALUE)
                .addComponent(applyBtn)
                .addGap(16, 16, 16))
        );

        centerPanel.add(jPanel6, java.awt.BorderLayout.EAST);

        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    private void setUpAction()
    {
        backBtn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                mainFrame.changePanel(new MinisterMenuPanel(mainFrame));
            }
        });
    }

    private void subjectNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectNameTFActionPerformed

    private void startDayTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDayTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDayTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSubjectBtn;
    private javax.swing.JButton applyBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton editBtn;
    private javax.swing.JTextField endDayTF;
    private javax.swing.JComboBox<String> endSessionCB;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> numberWeekCB;
    private javax.swing.JButton removeBtn;
    private javax.swing.JTextField roomNameTF;
    private javax.swing.JTextField startDayTF;
    private javax.swing.JComboBox<String> startSessionCB;
    private javax.swing.JTextField subjectIDTF;
    private javax.swing.JTextField subjectNameTF;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
