/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import javax.swing.*;
import javax.swing.border.*;
/**
 *
 * @author Windows 10
 */

public class MainPanel extends JPanel {

    /**
     * Creates new form mainPanel
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */


    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        topPanel = new JPanel();
        centerPanel = new JPanel();
        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jPanel2 = new JPanel();
        jPanel4 = new JPanel();
        usernameTF = new JTextField();
        jPanel5 = new JPanel();
        passwordTF = new JTextField();
        jPanel3 = new JPanel();
        signInBtn = new JButton();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.BorderLayout());

        topPanel.setMaximumSize(new java.awt.Dimension(800, 200));
        topPanel.setPreferredSize(new java.awt.Dimension(800, 150));

        GroupLayout topPanelLayout = new GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(topPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setMinimumSize(new java.awt.Dimension(500, 300));
        centerPanel.setPreferredSize(new java.awt.Dimension(581, 400));
        centerPanel.setLayout(new java.awt.GridLayout(1, 3));

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jLabel1.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel1.setText("Username: ");
        jLabel1.setVerticalAlignment(SwingConstants.BOTTOM);
        jLabel1.setAlignmentY(30.0F);
        jLabel1.setAutoscrolls(true);
        jLabel1.setBorder(new EmptyBorder(10,10,12,10)
        );
        jLabel1.setHorizontalTextPosition(SwingConstants.LEADING);
        jLabel1.setVerticalTextPosition(SwingConstants.BOTTOM);
        jPanel1.add(jLabel1);
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setHorizontalAlignment(SwingConstants.RIGHT);
        jLabel2.setText("Password: ");
        jLabel2.setVerticalAlignment(SwingConstants.TOP);
        jLabel2.setBorder(new EmptyBorder(12,10,10,10)
        );
        jPanel1.add(jLabel2);

        centerPanel.add(jPanel1);

        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        usernameTF.setBorder(null);
        usernameTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        usernameTF.setMaximumSize(new java.awt.Dimension(300, 30));
        usernameTF.setMinimumSize(new java.awt.Dimension(64, 24));
        usernameTF.setPreferredSize(new java.awt.Dimension(250, 24));
        usernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTFActionPerformed(evt);
            }
        });

        GroupLayout jPanel4Layout = new GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(usernameTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(usernameTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        usernameTF.getAccessibleContext().setAccessibleDescription("");

        jPanel2.add(jPanel4);

        passwordTF.setBorder(null);
        passwordTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        passwordTF.setMaximumSize(new java.awt.Dimension(300, 30));
        passwordTF.setMinimumSize(new java.awt.Dimension(64, 24));
        passwordTF.setPreferredSize(new java.awt.Dimension(250, 24));
        passwordTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTFActionPerformed(evt);
            }
        });

        GroupLayout jPanel5Layout = new GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(passwordTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(passwordTF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5);

        centerPanel.add(jPanel2);

        jPanel3.setBorder(new EmptyBorder(0,20,0,20)
        );
        jPanel3.setLayout(new BoxLayout(jPanel3, BoxLayout.LINE_AXIS));

        signInBtn.setText("Sign in");
        signInBtn.setAlignmentX(java.awt.Component.CENTER_ALIGNMENT);
        signInBtn.setAlignmentY(java.awt.Component.CENTER_ALIGNMENT);
        signInBtn.setHorizontalTextPosition(SwingConstants.CENTER);
        signInBtn.setMaximumSize(new java.awt.Dimension(80, 52));
        signInBtn.setPreferredSize(new java.awt.Dimension(80, 52));
        signInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInBtnActionPerformed(evt);
            }
        });
        jPanel3.add(signInBtn);

        centerPanel.add(jPanel3);

        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTFActionPerformed

    private void passwordTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTFActionPerformed

    private void signInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signInBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel centerPanel;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JPanel jPanel5;
    private JTextField passwordTF;
    private JButton signInBtn;
    private JPanel topPanel;
    private JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
