/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.student;

import javax.swing.*;

/**
 *
 * @author Windows 10
 */
public class CheckInItem extends javax.swing.JPanel {

    private JFrame mainFrame;
    /**
     * Creates new form CheckInItem
     */
    public CheckInItem(JFrame mainFrame) {
        this.mainFrame=mainFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        courseNameLB = new javax.swing.JLabel();
        scheduleLB = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        checkInBtn = new javax.swing.JButton();
        checkInStateLB = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nextTimeLB = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.BorderLayout());

        courseNameLB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        courseNameLB.setText("Course Name");
        jPanel6.add(courseNameLB, java.awt.BorderLayout.NORTH);

        scheduleLB.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        scheduleLB.setText("Schedule");
        scheduleLB.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel6.add(scheduleLB, java.awt.BorderLayout.CENTER);

        add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel5.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel7.setPreferredSize(new java.awt.Dimension(150, 50));

        checkInBtn.setText("CHECK IN");
        checkInBtn.setMaximumSize(new java.awt.Dimension(110, 40));
        checkInBtn.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel7.add(checkInBtn);

        checkInStateLB.setFont(new java.awt.Font("Yu Gothic Light", 0, 12)); // NOI18N
        checkInStateLB.setText("Check-in state");
        jPanel7.add(checkInStateLB);

        jPanel5.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setText("Next time check-in");
        jPanel8.add(jLabel6);

        nextTimeLB.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        nextTimeLB.setText("10-20-20002");
        jPanel8.add(nextTimeLB);

        jPanel5.add(jPanel8, java.awt.BorderLayout.CENTER);

        add(jPanel5, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkInBtn;
    private javax.swing.JLabel checkInStateLB;
    private javax.swing.JLabel courseNameLB;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel nextTimeLB;
    private javax.swing.JLabel scheduleLB;
    // End of variables declaration//GEN-END:variables
}
