/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.student;

import javax.swing.*;

/**
 *
 * @author Windows 10
 */
public class CheckInPanel extends javax.swing.JPanel {

    private JFrame mainFrame;
    /**
     * Creates new form CheckInPanel
     */
    public CheckInPanel(JFrame mainFrame) {
        this.mainFrame=mainFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        courseNameLB = new javax.swing.JLabel();
        scheduleLB = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        checkInBtn = new javax.swing.JButton();
        checkInStateLB = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nextTimeLB = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(627, 80));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("COURSE CHECK-IN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(372, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel3.setBorder(new javax.swing.border.EmptyBorder(10,10,10,10)
        );
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 100));

        jPanel4.setBackground(new java.awt.Color(204, 102, 0));
        jPanel4.setForeground(new java.awt.Color(255, 0, 51));
        jPanel4.setPreferredSize(new java.awt.Dimension(700, 125));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.BorderLayout());

        courseNameLB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        courseNameLB.setText("Course Name");
        jPanel6.add(courseNameLB, java.awt.BorderLayout.NORTH);

        scheduleLB.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        scheduleLB.setText("Schedule");
        scheduleLB.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel6.add(scheduleLB, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel5.setPreferredSize(new java.awt.Dimension(150, 100));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel7.setPreferredSize(new java.awt.Dimension(150, 50));

        checkInBtn.setText("CHECK IN");
        checkInBtn.setMaximumSize(new java.awt.Dimension(110, 40));
        checkInBtn.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel7.add(checkInBtn);

        checkInStateLB.setFont(new java.awt.Font("Yu Gothic Light", 0, 12)); // NOI18N
        checkInStateLB.setText("Check-in state");
        jPanel7.add(checkInStateLB);

        jPanel5.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setText("Next time check-in");
        jPanel8.add(jLabel6);

        nextTimeLB.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 12)); // NOI18N
        nextTimeLB.setText("10-20-20002");
        jPanel8.add(nextTimeLB);

        jPanel5.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel4);

        jScrollPane1.setViewportView(jPanel2);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkInBtn;
    private javax.swing.JLabel checkInStateLB;
    private javax.swing.JLabel courseNameLB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nextTimeLB;
    private javax.swing.JLabel scheduleLB;
    // End of variables declaration//GEN-END:variables
}
