/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.student;

import javax.swing.*;

/**
 *
 * @author Windows 10
 */
public class StudentMenuPanel extends javax.swing.JPanel {

    private JFrame mainFrame;
    /**
     * Creates new form StudentPanel
     */
    public StudentMenuPanel(JFrame mainFrame) {
        this.mainFrame=mainFrame;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        checkInBtn = new javax.swing.JButton();
        attendResultBtn = new javax.swing.JButton();
        changePassBtn = new javax.swing.JButton();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 150, 0};
        layout.rowHeights = new int[] {0, 80, 0};
        setLayout(layout);

        checkInBtn.setText("Check In");
        checkInBtn.setMaximumSize(new java.awt.Dimension(300, 50));
        checkInBtn.setMinimumSize(new java.awt.Dimension(150, 50));
        checkInBtn.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(checkInBtn, gridBagConstraints);

        attendResultBtn.setText("Attendance Result");
        attendResultBtn.setMaximumSize(new java.awt.Dimension(300, 50));
        attendResultBtn.setMinimumSize(new java.awt.Dimension(150, 50));
        attendResultBtn.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(attendResultBtn, gridBagConstraints);

        changePassBtn.setText("Change Password");
        changePassBtn.setMaximumSize(new java.awt.Dimension(300, 50));
        changePassBtn.setMinimumSize(new java.awt.Dimension(150, 50));
        changePassBtn.setPreferredSize(new java.awt.Dimension(200, 40));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        add(changePassBtn, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attendResultBtn;
    private javax.swing.JButton changePassBtn;
    private javax.swing.JButton checkInBtn;
    // End of variables declaration//GEN-END:variables
}
